# Generated by Django 2.1 on 2018-08-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=130)),
                ('keyword', models.TextField(blank=True, max_length=130)),
                ('start_date', models.TextField(blank=True, max_length=130)),
                ('end_date', models.TextField(blank=True)),
            ],
        ),
    ]
